> seq1
tactgtgatttcaactatacgacattctggaaaaggacaaactataaagacagtaaaaagatcagtggttatct
> seq2
ggagaggaaaccgggtaagatgtgtgaagcagtcggctataccaggcacagagaggacccactgggacacaaga
> seq3
cagaaaaggcaatttccttcctcttttctaatttggctctggagccaccagcagaacctcttcaatatcttgca
> seq4
tatcaggggaagacggtgctcgccttgacagaagctgtctatcgggctccagcggtcatgtccggcagaggaaa
> seq5
aaaggtgaagcagcggcgttttcggcgactttcccgatcgccaggcaggagtttctctcggtgactactatcgc
> seq6
aaagacggctgcggcggggctaggagctcgtttttctccccgccgctgcgctggtaagcctgtgttttggttcg
> seq7
atataaagggcccaggctcagggagctccatacctgcacacctccctctcacctgctcctctacctgctccacc
> seq8
ttggggtggagcgtcccgagacccgaaaacccagggcagagtgcccgtcagggtgatggttgaagtcctcacta
> seq9
atataaagggcccaggctcagggagctccatacctgcacacctccctctcacctgctcctctacctgctccacc
> seq10
atgttacaagtgataaactatgtattatgtgttatgttaaatgactgaaacatccctgtcttctcagtgcttcc
> seq11
ttatttttctttcctcatagttcagtgtcttcaaccaaccatggcaatattcaataacaccacttcgtcttcct
> seq12
tggtttcagatccggctaacgagctcatatctccctcattatgtctgttctcaataactccgaagtcaagcttt
> seq13
gaaccattcctcactacttgctgaattactcaaagtcactatgggagactggaataacagtgatgctgtggagc
> seq14
tctacatgtggcaagttctcctacactgtgatttggaaaaatgttttatcacaacaagagcatatttcacccag
> seq15
aaagaaaattcaagttctttgaaaattagaaataataactcagtgaatcttgaagtgccagagagatgttacaa
> seq16
ttatttttctttcctcatagttcagtgtcttcaaccaaccatggcaatattcaataacaccacttcgtcttcct
> seq17
tggtttcagatccggctaacgagctcatatctccctcattatgtctgttctcaataactccgaagtcaagcttt
> seq18
gaaccattcctcactacttgctgaattactcaaagtcactatgggagactggaataacagtgatgctgtggagc
> seq19
tctacatgtggcaagttctcctacactgtgatttggaaaaatgttttatcacaacaagagcatatttcacccag
> seq20
aacagcggaacggagacacggtggccgggccgaaaacgtcacaaagccgcagagagcgggctctgtcccgcccg
> seq21
gcgtcgcgggggcggggctcgggaaagacccgtgccagcgggcgtgtggccgcgggtttcgcacggtccaataa
> seq22
ggagcccctccctcatgagtgctgagcccaagggccaggctgtccccaggggcggagagttgcggacccttccc
> seq23
aggcgtgggtcccggaagctctgttctgcgggtggccgctcgcgcctgcgcagtggaggcggcccaggcccgcc
> seq24
gcctggccgtatcctcccccagagctgccccgttcagaccatggatcctgaggtgaccttgctgctgcagtgcc
> seq25
gcgatgcgggcgcccccggcgggcggccccggcgggcaccatgagccctctgctccgccgcctgctgctcgccg
> seq26
cacgttcagtcggtcggtcggggtctgtgcccacagagacatgaggctgagctggttccgggtcctgacagtac
> seq27
aagctcctccttctgcaccttgtcctgcaggaggtggctgatgccctgggagggggtgcggacccagaaaccaa
> seq28
ctgcgaacctatgggtctctccgtgcaggtgaccagcgccatgtccagccaggtggtgggcattgagcctctct
> seq29
tgatgattaagagtgacagcctgagggagctgagcgcagcatggctggtctggcagctgctgtcggtgtcgcga
> seq30
gtctcactccgtctgaattcctctccgtctccctcccaccccggccgtctatgctccaggccctctcctcgcgg
> seq31
accgcggccagggaaagcgcgtggagagccgaaaggtgcggtgggcgcagagggcgggctggctgcggggcgac
> seq32
gctggctgtgggttccctctgagatcagtgcggagctgtcaaagcgagcaggggtggcgccgggagtgggaacg
> seq33
aacaagagtaaaactccgtctaaaaaaaaagaaaaaaaaggacattgccagagtcttggcgatttggcccgacg
> seq34
tgccattatgacttgactcagctgggaaccacgagaggacgagatgacatctcttcaggatggtgtagagacgt
> seq35
ttgggtgcacgccctggggtggggcttcttcgggaagccgggggccttcaactctgctcaggagctcgggccgg
> seq36
cccgcgcgaggctgggaccggcggaaggggcgtggcctgcagaaggggcggggcgatagggatccagagtcttg
> seq37
acatctttgtcatttctctaagtgtttccagagcctggcaatggatgccattcacatcggcatgtccagcaccc
> seq38
aactgaggggtgcggatccgggccccccagcctgcgaagcgcactcgcaggtcgagcgggcgtcgtccaccctt
> seq39
aactgaggggtgcggatccgggccccccagcctgcgaagcgcactcgcaggtcgagcgggcgtcgtccaccctt
> seq40
gaaagtcatggatgaataattacgtctgtggttttctatggaggttccatgtcagataaagatccttccgacgc
> seq41
gcaattttaaatctatatatagagatatctttgtcagcattgcatcgttagcttctcctgataaactaattgcc
> seq42
cccggcggcgccccaggctgcagtgttccgggagctgggttataaaatgccgggttaagcggcaactcagactc
> seq43
cacctgtaaggcgagcgcggcgcgggggatggaagcaggcgcccattggacagaatacaaaggcagaaacctac
> seq44
cagtggcatccccctcaaggcctggctccatgattctgagaggactagaatcaggacagtcagatctgtggtca
> seq45
gaaagtcatggatgaataattacgtctgtggttttctatggaggttccatgtcagataaagatccttccgacgc
> seq46
ttcctctgtgtatttaagagctcttttgccagtgagcccagtacacagagagaaaggctaaagttctctggagg
> seq47
acttgggcctataaaagctgccacaagacgccaaggccacaagccacccagcctatgcatccgctcctcaatcc
> seq48
cccggcggcgccccaggctgcagtgttccgggagctgggttataaaatgccgggttaagcggcaactcagactc
> seq49
cacctgtaaggcgagcgcggcgcgggggatggaagcaggcgcccattggacagaatacaaaggcagaaacctac
> seq50
cagtggcatccccctcaaggcctggctccatgattctgagaggactagaatcaggacagtcagatctgtggtca
> seq51
ggatggaacacagagcgcggccgggacaaaggggcaggccagacagccgtgacagagaaactaggcggtccgct
> seq52
ggcccaggcagaaccgcggttctagtctcccagctccagctcggcctttgggtttgctgtggtgtccttgtctc
> seq53
ggcccaggcagaaccgcggttctagtctcccagctccagctcggcctttgggtttgctgtggtgtccttgtctc
> seq54
cagtctcccaggtcccagctggggctgacgtcgtcctggtgtgtgcccaaaatagccggctccgccctcttctc
> seq55
gtcaggagggatacaaatagtgccgacggctgggggccctgtctcccctcgccgcatccactctccggccggcc
> seq56
atacctgcttcgcaccccatgcgcctaaccacaaggttccctccctccaggaaggccgttgtcttccctgggac
> seq57
atacctgcttcgcaccccatgcgcctaaccacaaggttccctccctccaggaaggccgttgtcttccctgggac
> seq58
gggtttcctttcatcttcgctgtggcagacgtttctatttatccacttgcgctcgccgagtggcgtcaccagcg
> seq59
ttaaaagaaccaggaaacagcacatgatctgttggaaggaggcattcattctttcctttctgtgggtgtgggga
> seq60
ggagcgggagctgcgggattccggcttcaggggcggggcaccggcctctgggcggagatctgctgccgcgttct
> seq61
gtaccgttgccaggatgtgacgccactgacttgcgcattggaggtcagaagaccgcgagattctcgccctgagc
> seq62
cgggcccggatgtgacgccactgacttgcgcattggaggtcagaggacagcgagattctcgccctgagcaacgg
> seq63
cctgcggtctcccggacgacgcggaggggtccgcgctgcaccgccgccgcgcccccgccccgtgtccgcactgc
> seq64
ccccggccgcgtgaccgcactgcagagagcggctgcgagcaggcgcctgcgcaccggcccaaacgccgagcgag
> seq65
ccccgcttcctgccgcggggcctgaggcgcctgacgctgcaccacgaccacatcgagcgcatccctggctacgc
> seq66
ccccgcttcctgccgcggggcctgaggcgcctgacgctgcaccacgaccacatcgagcgcatccctggctacgc
> seq67
cgccacccggggttccggtggcgttaggctgcagcagtggcgcttcccgccgcccgagcttcggaaacttcccg
> seq68
ggccccgccctctccgccgctagccaatcctcgcgttgatgacgtttgggctcgcggccccagcctcccagctc
> seq69
gtggggcggggcgcgcgcggctcccgcgcacggattcttcctgggccgcagcaccggccgccggcccgccccgc
> seq70
tgcccatctcacgccagggggcggaacttcctgcagcctctctgcctccgcatcctcgtgggccctgaccttct
> seq71
cgccacccggggttccggtggcgttaggctgcagcagtggcgcttcccgccgcccgagcttcggaaacttcccg
> seq72
aaagtgctgagatcacaggcgtgagccacggcactccgccgcaattcctgacttgtactgccccagtggtgtta
> seq73
gtggggcggggcgcgcgcggctcccgcgcacggattcttcctgggccgcagcaccggccgccggcccgccccgc
> seq74
tgcccatctcacgccagggggcggaacttcctgcagcctctctgcctccgcatcctcgtgggccctgaccttct
> seq75
gaggcagttggagaccaggtcctgccctgttagcctttctgtaggaccaggtgtcacactcatctgagggctcc
> seq76
ctctggccaacaccccctgtaaggccacaggagaggaacaggagtgatagcccccaaaccccagtcccaccagg
> seq77
aatgagcgccgcccggccgggcgtgcccccgcgccccaagcataaaccctggcgcgctcgcgggccggcactct
> seq78
ctgctgcttggcttctggcccccttatctgcccccgccccacgcgccctggcagcaccatgagccgccagcttc
> seq79
gcctactcgtcctggccgcagagtcagcgtctccggagcgcctccttctcccgccctggggctcacgtgggaat
> seq80
cccgcgcgaggctgggaccggcggaaggggcgtggcctgcagaaggggcggggcgatagggatccagagtcttg
> seq81
atacctgcttcgcaccccatgcgcctaaccacaaggttccctccctccaggaaggccgttgtcttccctgggac
